version: "3.9"
services:
  api:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      GIN_MODE: release
      POSTGRES_URL: postgresql://postgres:postgres@db:5432/gobank_users?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gobank_users
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
