// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: unary/proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SomethingServiceClient is the client API for SomethingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SomethingServiceClient interface {
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
}

type somethingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSomethingServiceClient(cc grpc.ClientConnInterface) SomethingServiceClient {
	return &somethingServiceClient{cc}
}

func (c *somethingServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, "/SomethingService/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SomethingServiceServer is the server API for SomethingService service.
// All implementations should embed UnimplementedSomethingServiceServer
// for forward compatibility
type SomethingServiceServer interface {
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
}

// UnimplementedSomethingServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSomethingServiceServer struct {
}

func (UnimplementedSomethingServiceServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}

// UnsafeSomethingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SomethingServiceServer will
// result in compilation errors.
type UnsafeSomethingServiceServer interface {
	mustEmbedUnimplementedSomethingServiceServer()
}

func RegisterSomethingServiceServer(s grpc.ServiceRegistrar, srv SomethingServiceServer) {
	s.RegisterService(&SomethingService_ServiceDesc, srv)
}

func _SomethingService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SomethingServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SomethingService/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SomethingServiceServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SomethingService_ServiceDesc is the grpc.ServiceDesc for SomethingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SomethingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SomethingService",
	HandlerType: (*SomethingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _SomethingService_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "unary/proto/service.proto",
}
